version: '3.9'

services:
  backend:
    image: ch0musuk33/uit-fms-backend:latest
    container_name: uit_fms_backend
    restart: unless-stopped

  environment:
    PORT: 3001

    DB_HOST: postgres
    DB_PORT: 5432
    DB_USER: postgres
    DB_PASS: 123456
    DB_NAME: uit_fms

    DATABASE_URL: postgresql://postgres:123456@postgres:5432/uit_fms

    REDIS_URL: redis://redis:6379

    JWT_SECRET: ${JWT_SECRET}

    GMAIL_USER: lamanhkhoa2004@gmail.com
    GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    GMAIL_FROM: lamanhkhoa2004@gmail.com

    SENDGRID_API_KEY: ${SENDGRID_API_KEY}

  ports:
    - "3001:3001"

  depends_on:
    - postgres
    - redis

  watchtower:
    image: containrrr/watchtower

    container_name: watchtower

    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: --interval 30 --cleanup

  postgres:
    image: postgres:15
    container_name: uit_fms_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: uit_fms

    ports:
      - '5439:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: uit_fms_redis
    restart: unless-stopped

    ports:
      - '6379:6379'

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: